### ISSUE TITLE
US vs UK English

### ISSUE THREAD

**Issue by MobileMon** [x-englishwordnet/sqlite#1]
How can I query on US vs UK English?

For instance, the word analyze vs analyse

I want to filter out all words that have UK spelling

**Comment by 1313ou** [comment]
Start with this:

```
SELECT w1.word,relation,w2.word,s1.definition,s2.definition,w2.wordid,s2.synsetid 
FROM lexrelations 
LEFT JOIN synsets AS s1 ON (s1.synsetid = synset1id) 
LEFT JOIN synsets AS s2 ON (s2.synsetid = synset2id) 
LEFT JOIN words AS w1 ON (w1.wordid = word1id) 
LEFT JOIN words AS w2 ON (w2.wordid = word2id) 
LEFT JOIN relations USING(relationid) 
WHERE w1.word IN ('analyze','analyse') AND relation = 'exemplifies'
```
you'll get:

#### word, relation, word, definition, definition, wordid, synsetid
analyse, exemplifies, australian spelling, subject to psychoanalytic treatment, English orthography used in Australia (characterized by 'analyse', 'centre', 'usable'), 10196, 117795
analyse, exemplifies, british spelling, subject to psychoanalytic treatment, English orthography used in the UK, Ireland and most of the Commonwealth (characterized by 'analyse', 'centre' and 'useable'), 18078, 117833
analyse, exemplifies, australian spelling, make a mathematical, chemical, or grammatical analysis of; break down into components or essential features, English orthography used in Australia (characterized by 'analyse', 'centre', 'usable'), 10196, 117795
analyse, exemplifies, british spelling, make a mathematical, chemical, or grammatical analysis of; break down into components or essential features, English orthography used in the UK, Ireland and most of the Commonwealth (characterized by 'analyse', 'centre' and 'useable'), 18078, 117833
analyse, exemplifies, australian spelling, consider in detail and subject to an analysis in order to discover essential features or meaning, English orthography used in Australia (characterized by 'analyse', 'centre', 'usable'), 10196, 117795
analyse, exemplifies, british spelling, consider in detail and subject to an analysis in order to discover essential features or meaning, English orthography used in the UK, Ireland and most of the Commonwealth (characterized by 'analyse', 'centre' and 'useable'), 18078, 117833
analyse, exemplifies, australian spelling, break down into components or essential features, English orthography used in Australia (characterized by 'analyse', 'centre', 'usable'), 10196, 117795
analyse, exemplifies, british spelling, break down into components or essential features, English orthography used in the UK, Ireland and most of the Commonwealth (characterized by 'analyse', 'centre' and 'useable'), 18078, 117833
analyze, exemplifies, american spelling, subject to psychoanalytic treatment, English orthography used in the United States (characterized by 'analyze', 'center', 'usable'), 4908, 117840
analyze, exemplifies, american spelling, make a mathematical, chemical, or grammatical analysis of; break down into components or essential features, English orthography used in the United States (characterized by 'analyze', 'center', 'usable'), 4908, 117840
analyze, exemplifies, american spelling, consider in detail and subject to an analysis in order to discover essential features or meaning, English orthography used in the United States (characterized by 'analyze', 'center', 'usable'), 4908, 117840
analyze, exemplifies, american spelling, break down into components or essential features, English orthography used in the United States (characterized by 'analyze', 'center', 'usable'), 4908, 117840


then you can fine-tune what you want and what you start from.
note you can simplify by hardcoding relationid, w2.wordid, s2.synsetid  in the where clause

**Comment by MobileMon** [comment]
thanks for the help but I'm still struggling

What I'm trying to do is pull a random word, that is either denoted as american spelling or none at all. So basically filtering out any UK/Australia/Canadian

Here is my query. How can I do the filter here?

`SELECT w.wordid, w.word 
        FROM words as w 
        ORDER BY RANDOM() 
        LIMIT 1`
